Implement Auth
fedyafedko/StudyHub pull request #20
Opened 2023-11-16 19:59 UTC by Podgore

2023-11-16 21:24 UTC, fedyafedko commented on StudyHub/StudyHub.DAL/Repositories/UserRepository.cs
Delete UserRepository and use UserManager. URL:https://metanit.com/sharp/aspnet5/16.11.php

2023-11-16 21:24 UTC, fedyafedko commented on StudyHub/StudyHub.Common/DTO/LoginUserDTO.cs
fix all warnings

2023-11-16 21:24 UTC, fedyafedko commented on StudyHub/StudyHub/appsettings.json
Return the connection string and create another local json file and add your connection string there. Also leave the JwtSettings here and add to the local json file

2023-11-16 21:40 UTC, aquaprogit commented on StudyHub/StudyHub/appsettings.json
Fedya meant adding local appsettings.development.json and using it locally, and common appsettings.json should contain shared data or placeholders like connection_string

2023-11-16 21:45 UTC, aquaprogit requested changes

2023-11-16 21:45 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/EF/ApplicationDbContextFactory.cs
> +        var connectionString = "Server=(local);Database=StudyHub;Trusted_Connection=True;TrustServerCertificate=true;";
Maybe try to get this from appsettings excluding literal directly from file

2023-11-16 21:45 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/Repositories/Repository.cs
> +    public DbSet<TEntity> _table;
No need to make it public

2023-11-18 18:14 UTC, fedyafedko commented on StudyHub/StudyHub/Controllers/AuthController.cs
Add try catch for controllers

2023-11-18 18:14 UTC, fedyafedko commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
add refresh token

2023-11-18 18:14 UTC, fedyafedko commented on StudyHub/StudyHub.BLL/AutoMapper/UserProfile.cs
why a profile if you didn't use a mapper ?

2023-11-19 13:35 UTC, Podgore commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
It need to be done by another task, I'll register it

2023-11-19 17:09 UTC, fedyafedko approved these changes

2023-11-19 18:22 UTC, aquaprogit requested changes

2023-11-19 18:22 UTC, aquaprogit commented on .gitignore
> +/StudyHub/StudyHub/appsettings.develop.json
need to be removed and rename your local appsettings to **appsettings.Development.json**

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/Entities/StudyHub.Entities.csproj
> +    <PackageReference Include="AutoMapper" Version="12.0.1" />
Is AutoMapper needed in this csproj?

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/Entities/Subject.cs
> +    public User User { get; set; } = null!;
Why used User here?

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
> +
empty line should be removed

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
> +        var existingUser = await _userManager.FindByEmailAsync(user.Email!);
why user.Email can be null?

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.Common/DTO/LoginUserDTO.cs
Why nullable props for mandatory fields?

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.Common/DTO/RegisterUserDTO.cs
Same. How is it possible to register with all null?

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.Common/StudyHub.Common.csproj
> +    <PackageReference Include="AutoMapper" Version="12.0.1" />
Is AutoMapper needed in this csproj?

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/EF/ApplicationDbContext.cs
Discuss which method you shall use in your project, Fluent builder or Attribute usage (_currently both, unacceptable_)

2023-11-19 18:22 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/StudyHub.DAL.csproj
> +    <PackageReference Include="AutoMapper" Version="12.0.1" />
Is AutoMapper needed in this csproj?

2023-11-19 20:39 UTC, aquaprogit approved these changes

2023-11-19 20:58 UTC, aquaprogit approved these changes

2023-11-19 20:59 UTC, fedyafedko approved these changes

2023-11-19 20:59 UTC, merged