AssignmentTask Controller implementation#17
fedyafedko/StudyHub pull request #21
Opened 2023-11-17 11:39 UTC by fedyafedko

2023-11-17 12:42 UTC, Podgore commented on StudyHub/StudyHub.Common/DTO/AssignmentTaskOption/AssignmentTaskOptionDTO.cs
> +    public string Label { get; set; }
fix warnings

2023-11-17 12:42 UTC, Podgore commented on StudyHub/StudyHub/Controllers/AssignmentTaskController.cs
> +    public async Task<IActionResult> InsretTask(CreateAssignmentTaskDTO dto)
fix naming

2023-11-17 13:08 UTC, aquaprogit requested changes

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AssignmentTaskService.cs
> +        if (_repositoryAssignment.FirstOrDefault(option => option.Id == dto.AssignmentId) == null)
```suggestion
        if (await _repositoryAssignment.FirstOrDefaultAsync(assignment => assignment.Id == dto.AssignmentId) == null)
```

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/OptionsService.cs
> +            var nullOptions = taskOption
what is purpose of this?

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub.Common/DTO/AssignmentTask/CreateAssignmentTaskDTO.cs
> +    public List<AssignmentTaskOptionDTO> Options { get; set; } = null!;
consistency missing

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub.Common/DTO/AssignmentTask/AssignmentTaskDTO.cs
> +    public List<AssignmentTaskOptionDTO> Options { get; set; } = new List<AssignmentTaskOptionDTO>();
consistency missing

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/Repositories/Repository.cs
> +    private readonly DbSet<TEntity> _table;
why do you need empty space here?

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub/Controllers/AssignmentTaskController.cs
> +    public async Task<IActionResult> InsretTask(CreateAssignmentTaskDTO dto)
```suggestion
    public async Task<IActionResult> InsertTask(CreateAssignmentTaskDTO dto)
```

2023-11-17 13:08 UTC, aquaprogit commented on StudyHub/StudyHub/Program.cs
> +builder.Services.AddAutoMapper(typeof(OptionsProfile).Assembly);
I don't think that you need to add mapper for every profile
Check documentation about this

2023-11-17 14:19 UTC, aquaprogit requested changes

2023-11-17 20:06 UTC, aquaprogit submitted a review, later dismissed

2023-11-18 14:34 UTC, aquaprogit approved these changes

2023-11-18 15:51 UTC, Podgore approved these changes

2023-11-18 15:52 UTC, Podgore approved these changes

2023-11-18 15:55 UTC, merged