feat:add refresh token
fedyafedko/StudyHub pull request #27
Opened 2023-11-27 19:28 UTC by Podgore

2023-11-28 13:06 UTC, aquaprogit requested changes

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
> +
empty line should be removed, I guess

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
> +            {
remove curly brackets for this if

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
> +        return validatedToken is JwtSecurityToken jwtSecurityToken &&
fix formatting

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.Common/DTO/AuthDTO/RefreshTokenRequest.cs
> +
empty line

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.Common/Exceptions/ExpiredError.cs
> +    public ExpiredError
formatting

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.Common/Exceptions/IncorrectParametersError.cs
> +    public IncorrectParametersError
also formatting

2023-11-28 13:06 UTC, aquaprogit commented on StudyHub/StudyHub.Common/Exceptions/InvalidSecurityAlgorithmException.cs
> +    public InvalidSecurityAlgorithmException
same and for others Exceptions

2023-11-29 08:12 UTC, fedyafedko approved these changes

2023-11-29 08:49 UTC, aquaprogit approved these changes

2023-11-29 08:52 UTC, aquaprogit requested changes
rename "Errors" in StudyHub.Common.**Exceptions**

2023-11-29 18:58 UTC, aquaprogit requested changes

2023-11-29 18:58 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
> +            ExpiryDate = DateTime.Now.AddDays(7),
better to move this to config

2023-11-29 18:58 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/AuthService.cs
>          var result = await _userManager.CheckPasswordAsync(existingUser, user.Password);
name it as "isPasswordValid"
use appropriate naming for variables

2023-11-29 19:21 UTC, aquaprogit approved these changes

2023-11-30 12:13 UTC, merged