feat: add teacher, student, admin controller implementation
fedyafedko/StudyHub pull request #33
Opened 2023-12-06 20:52 UTC by Podgore

2023-12-07 10:09 UTC, fedyafedko commented on StudyHub/StudyHub.BLL/Services/UserInvitedService.cs
> +    private readonly IRepository<InvitedUsers> _repoInvitedUsers;
Maybe better _repositoryInvitedUsers

2023-12-07 10:37 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/UserInvitedService.cs
> +    private readonly IRepository<InvitedUsers> _repoInvitedUsers;
_invitedUserRepository

2023-12-09 20:29 UTC, fedyafedko requested changes

2023-12-19 23:01 UTC, fedyafedko requested changes

2023-12-20 22:02 UTC, fedyafedko requested changes

2023-12-20 22:02 UTC, fedyafedko commented on StudyHub/StudyHub/appsettings.json
> +    "MessagePath": "E:\\C\\StudyHub\\StudyHub\\StudyHub.FluentEmail\\MessageToSend.cshtml"
no use local path

2023-12-21 10:22 UTC, fedyafedko submitted a review, later dismissed

2024-01-14 01:00 UTC, fedyafedko approved these changes

2024-01-14 01:21 UTC, aquaprogit approved these changes

2024-01-14 01:24 UTC, merged