feat: implement google OAuth 2.0
fedyafedko/StudyHub pull request #34
Opened 2023-12-10 22:21 UTC by fedyafedko

2023-12-11 19:21 UTC, aquaprogit requested changes

2023-12-11 19:21 UTC, aquaprogit commented on StudyHub/StudyHub/Controllers/GoogleAuthController.cs
> +    [ActionName("sign-in")]
remove this attribute, use HttpPostAttribute param instead

2023-12-11 20:17 UTC, aquaprogit approved these changes

2023-12-14 11:35 UTC, Podgore approved these changes

2023-12-14 11:50 UTC, merged