feat: add clearning invitation users
fedyafedko/StudyHub pull request #51
Opened 2024-01-17 12:05 UTC by fedyafedko

2024-01-17 12:22 UTC, Podgore requested changes

2024-01-17 12:22 UTC, Podgore commented on StudyHub/StudyHub.BLL/Services/HangfireService.cs
> +        return _invitedUserRepository.DeleteMany(remainingUsers);
Are we needed there async, maybe?

2024-01-17 12:34 UTC, Podgore submitted a review, later dismissed

2024-01-17 18:49 UTC, Podgore requested changes

2024-01-17 18:49 UTC, Podgore commented on StudyHub/StudyHub.Hangfire/HangfireConfig.cs
> +    public string ClearingUserInvitationCron { get; set; }
some warnings here

2024-01-17 18:49 UTC, Podgore commented on StudyHub/StudyHub.Hangfire/Abstractions/IHangfireService.cs
> +﻿namespace StudyHub.Hangfire.Abstractions;
empty line)

2024-01-17 18:49 UTC, Podgore commented on StudyHub/StudyHub.Hangfire/Abstractions/IJobArgs.cs
are we need that empty interface?

2024-01-17 18:49 UTC, Podgore commented on StudyHub/StudyHub.Hangfire/Extensions/HangfireExtensions.cs
> +namespace StudyHub.Hangfire.Extensions;
empty line

2024-01-17 18:49 UTC, Podgore commented on StudyHub/StudyHub.BLL/Services/UserInvitationService.cs
> +    public async Task ClearExpiredInvitations()
maybe ClearExpiredInvintationsAsync?

2024-01-17 20:30 UTC, Podgore submitted a review, later dismissed

2024-01-18 09:21 UTC, aquaprogit requested changes

2024-01-18 09:21 UTC, aquaprogit commented on StudyHub/StudyHub/Program.cs
> +builder.Services.AddScoped<IHangfireService, HangfireService>();
move this up to AddHangfire extensions

2024-01-18 09:21 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/UserInvitationService.cs
> +            .Where(user => user.CreatedAt.AddDays(7) <= DateTime.Today);
move count of days (or lifetime in TimeSpan) to config

2024-01-18 10:34 UTC, aquaprogit approved these changes

2024-01-18 11:26 UTC, Podgore approved these changes

2024-01-18 11:26 UTC, merged