Config adding mechanism #55
fedyafedko/StudyHub pull request #64
Opened 2024-01-20 22:42 UTC by fedyafedko

2024-01-21 12:02 UTC, Podgore requested changes

2024-01-21 12:02 UTC, Podgore commented on StudyHub/StudyHub.Common/Configs/UserInvitationConfig.cs
> +﻿namespace StudyHub.Common.Configs;
empty line

2024-01-21 12:02 UTC, Podgore commented on StudyHub/StudyHub.Common/Configs/ConfigBase.cs
> +﻿namespace StudyHub.Common.Configs;
empty line

2024-01-21 12:11 UTC, Podgore submitted a review, later dismissed

2024-01-21 14:12 UTC, aquaprogit commented on StudyHub/StudyHub/Program.cs
> +builder.Services.AddConfig<JwtConfig>(builder.Configuration);
I think we can avoid passing the same builder.Configuration for every AddConfig call

2024-01-21 14:12 UTC, aquaprogit commented on StudyHub/StudyHub/Extensions/ConfigExtension.cs
> +        return services.Configure<T>(configuration.GetSection(typeof(T).Name));
this adds config to DI as IOptions\<T\>, maybe we can directly add Config instance

2024-01-22 12:53 UTC, aquaprogit approved these changes

2024-01-22 21:04 UTC, merged