Update schema
fedyafedko/StudyHub pull request #65
Opened 2024-01-21 16:26 UTC by Podgore

2024-01-22 13:05 UTC, aquaprogit requested changes

2024-01-22 13:05 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/EF/ApplicationDbContext.cs
> +        modelBuilder.Entity<TaskOption>()
move this to separate IEntityTypeConfiguration

2024-01-23 09:30 UTC, fedyafedko approved these changes

2024-01-24 13:14 UTC, aquaprogit requested changes

2024-01-24 13:14 UTC, aquaprogit commented on StudyHub/StudyHub.DAL/EF/ApplicationDbContext.cs
> +        new SubjectConfiguration().Configure(modelBuilder.Entity<Subject>());
modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly);

2024-01-24 13:25 UTC, fedyafedko approved these changes

2024-01-24 14:46 UTC, merged