Implement functionality for editing the user profile #66
fedyafedko/StudyHub pull request #70
Opened 2024-01-25 17:25 UTC by fedyafedko

2024-01-25 18:11 UTC, Podgore commented on StudyHub/StudyHub.BLL/Profiles/UserProfile.cs
>          CreateMap<User, UserDTO>();
empty line

2024-01-25 18:14 UTC, Podgore commented on StudyHub/StudyHub.Common/DTO/UserInvitation/UpdateUserDTO.cs
> +﻿namespace StudyHub.Common.DTO.UserInvitation;
emtpy line

2024-01-25 18:18 UTC, Podgore requested changes

2024-01-25 18:18 UTC, Podgore commented on StudyHub/StudyHub/Validators/UserValidators/UpdateUserValidator.cs
> +            .NotEmpty();
add regex for validation

2024-01-25 18:18 UTC, Podgore commented on StudyHub/StudyHub/Validators/UserValidators/UpdateUserValidator.cs
> +            .NotEmpty();
also add some regex for validation

2024-01-25 19:15 UTC, Podgore submitted a review, later dismissed

2024-01-25 22:08 UTC, aquaprogit requested changes

2024-01-25 22:08 UTC, aquaprogit commented on StudyHub/StudyHub/Controllers/UsersController.cs
> +    [HttpPut("[action]")]
```suggestion
    [HttpPut("me")]
```

2024-01-25 22:08 UTC, aquaprogit commented on StudyHub/StudyHub/Controllers/UsersController.cs
> +        var result = await _userService.EditAsync(userId, dto);
get userId from HttpContext

2024-01-25 22:08 UTC, aquaprogit commented on StudyHub/StudyHub.Common/Utility/ValidationRegexes.cs
> +    public const string Telegram = @".*?\B@\w{5}.*";
check Telegram actual regex

2024-01-26 08:58 UTC, aquaprogit approved these changes

2024-01-26 08:58 UTC, aquaprogit commented on StudyHub/StudyHub.Common/Utility/ValidationRegexes.cs
> +    public const string Telegram = @"^@[a-zA-Z0-9_]+";
![image](https://github.com/fedyafedko/StudyHub/assets/43469966/0ea6a526-044a-47a2-bd39-ef0f8bc64b29)
keep it like it was

2024-01-26 08:58 UTC, aquaprogit commented on StudyHub/StudyHub.BLL/Services/Interfaces/IUserService.cs
> +    Task<PageList<StudentDTO>> GetStudents(SearchRequest request);
Async

2024-01-26 09:21 UTC, aquaprogit approved these changes

2024-01-26 13:23 UTC, Podgore approved these changes

2024-01-26 13:24 UTC, merged